services:
  - type: web
    name: nurse-report
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GROQ_API_KEY
        value: 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
